version: '3.8'

services:
  nucleo_backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
